version: '3.7'
services:
  webfms2:
    image: webfms:python3.6
    restart: "no"
    #restart: always
    hostname: ${WEB_TAG}
    container_name: ${WEB_TAG}
    ports:
      - "${PORT}:80"
      #- "443:443"

    volumes:
      # ---------------- code  ----------------
      - ~/server.viewtec/code:/app
      #- /media/vdisk:/media/vdisk
      # - /media/vdisk/fws:/media/vdisk/fws
      # - ~/docker/uwsgi/webfms.conf:/etc/nginx/conf.d/webfms.conf
      # ---------------- nginx  ----------------
      #- ~/docker/uwsgi/docker_config/nginx.conf:/etc/nginx/nginx.conf 在app的目錄下
      #- /tmp:/var/cache/nginx
      - ./docker_config/nginx.conf:/app/nginx.conf
      - ./docker_config/server.conf:/etc/nginx/server.conf
      #- ./docker_config/location_v0.5.conf:/etc/nginx/location_v0.5.conf
      - ./docker_config/uwsgi.ini:/app/uwsgi.ini
      - ./docker_config/uwsgi.ini:/etc/uwsgi/uwsgi.ini
      # -----------------log -------------------
      #- /tmp:/var/log/nginx
      #- /tmp:/var/log/supervisor
      #- /tmp:/tmp
      
      - type: bind
        source: /tmp/uwsgi_0.5_${WEB_TAG}.log
        target: /tmp/uwsgi_0.5.log

      - type: bind
        source: /tmp/supervisord_${WEB_TAG}.log
        target: /var/log/supervisor/supervisord.log

      - type: bind
        source: /tmp/access_${WEB_TAG}.log
        target: /var/log/nginx/access.log

      - type: bind
        source: /tmp/error_${WEB_TAG}.log
        target: /var/log/nginx/error.log



    #ulimits:
    #  nofile:
    #    soft: 98304
    #    hard: 98304
