version: '3.4'                                                                                                                                                                        
services:
  webapp:
    image: webapp
    restart: "no"
    #restart: always
    hostname: webapp
    container_name: webapp
    ports:
      - "9999:6666"
      #- "443:443"
    volumes:
      # ---------------- code  ----------------
      - ~/webapp/app:/app
      #- /media/vdisk:/media/vdisk
      # - /media/vdisk/fws:/media/vdisk/fws
      # - ~/docker/uwsgi/webfms.conf:/etc/nginx/conf.d/webfms.conf
      # ---------------- nginx  ----------------
      #- ~/docker/uwsgi/docker_config/nginx.conf:/etc/nginx/nginx.conf 在app的目錄下
      #- /tmp:/var/cache/nginx
      #- ./docker_config/nginx.conf:/app/nginx.conf
      #- ./docker_config/server.conf:/etc/nginx/server.conf
      #- ./docker_config/location_v0.5.conf:/etc/nginx/location_v0.5.conf
      #- ~/webapp/uwsgi.ini:/app/uwsgi.ini
      - /tmp:/tmp
